apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-api
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
      - name: api
        env:
        - name: MICRO_PROXY
          value: "go.micro.api"
        - name: MICRO_ENABLE_STATS
          value: "true"
        - name: MICRO_REGISTRY
          value: "consul"
        - name: MICRO_REGISTRY_ADDRESS
          value: "consul-consul-server"
        - name: MICRO_REGISTER_TTL
          value: "60"
        - name: MICRO_REGISTER_INTERVAL
          value: "30"
        - name: MICRO_ENABLE_ACME
          value: "true"
        args:
        - api
        image: microhq/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: api-port
