apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-init
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-init
subjects:
- kind: ServiceAccount
  name: micro-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-init
  labels:
    micro: service
    name: micro-init
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-init
      micro: service
  template:
    metadata:
      labels:
        name: micro-init
        micro: service
    spec:
      serviceAccountName: micro-init
      containers:
      - name: init
        env:
        - name: MICRO_NAMESPACE
          value: "micro"
        - name: MICRO_RUNTIME
          value: "kubernetes"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        args:
        - init
        image: micro/micro
        imagePullPolicy: Always
