apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-monitor
  template:
    metadata:
      labels:
        name: micro-monitor
    spec:
      containers:
        - name: monitor
          command: [
            "/micro",
            "monitor",
          ]
          image: micro/micro
          imagePullPolicy: Always
          env:
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats-cluster"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
