apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: network-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: network-api
  template:
    metadata:
      labels:
        name: network-api
    spec:
      containers:
        - name: network-api
          command: [
                "/micro",
                "--server_address=0.0.0.0:9090",
                "--broker_address=0.0.0.0:10001"
                "network",
                "api",
          ]
          env:
          - name: MICRO_PROXY
            value: "go.micro.proxy"
          - name: MICRO_REGISTRY
            value: "consul"
          - name: MICRO_REGISTRY_ADDRESS
            value: "consul-consul-server"
          image: microhq/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: api-port
