apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-registry
  labels:
    micro: service
    name: micro-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      name: micro-registry
      micro: service
  template:
    metadata:
      labels:
        name: micro-registry
        micro: service
    spec:
      containers:
      - name: registry
        env:
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        args:
        - registry
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: registry-port
