apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-router
  labels:
    micro: service
    name: micro-router
spec:
  replicas: 3
  selector:
    matchLabels:
      name: micro-router
      micro: service
  template:
    metadata:
      labels:
        name: micro-router
        micro: service
    spec:
      containers:
      - name: router
        env:
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_GATEWAY_ADDRESS
          value: "micro-gateway:8080"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_ENABLE_ACME
          value: "true"
        args:
        - router
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: router-port
