apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-store
  labels:
    micro: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-store
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-store
        micro: runtime
    spec:
      containers:
      - name: micro-store
        env:
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_STORE_BACKEND
          value: "cockroach"
        - name: MICRO_STORE_NODES
          value: "host=cockroachdb-public port=26257 sslmode=disable user=root"
        image: micro/micro
        imagePullPolicy: Always
        command:
        - /micro
        - store
