apiVersion: v1
kind: Service
metadata:
  name: micro-network
  namespace: default
  labels:
    micro: runtime
    name: network
    version: latest
spec:
  ports:
  - port: 8085
    protocol: UDP
    name: network-udp
    targetPort: 8085
  - port: 8443
    protocol: TCP
    name: network-tcp
    targetPort: 8443
  selector:
    name: micro-network
    micro: runtime
