apiVersion: v1
kind: Service
metadata:
  name: micro-auth-api
  namespace: default
  labels:
    name: micro-auth-api
    micro: runtime
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    name: micro-auth-api
    micro: runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-auth-api
  labels:
    micro: runtime
    name: micro-auth-api
  annotations:
    name: "go.micro.api.auth"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-auth-api
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-auth-api
        micro: runtime
    spec:
      containers:
      - name: auth
        env:
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_AUTH
          value: "service"
        args:
        - auth
        - api
        image: bentoogood/micro:mtls
        imagePullPolicy: Always
        ports:
        - containerPort: 8011
          name: auth-port
