apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-auth
  labels:
    micro: runtime
    name: micro-auth
  annotations:
    name: "go.micro.auth"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-auth
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-auth
        micro: runtime
    spec:
      containers:
      - name: auth
        env:
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_STORE
          value: "cockroach"
        - name: MICRO_STORE_ADDRESS
          value: "postgres://root@cockroachdb-public:26257/?sslmode=disable"
        - name: MICRO_STORE_NAMESPACE
          value: "auth"
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-keypair
              key: public
        args:
        - auth
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: auth-port
