apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-bot
  labels:
    micro: runtime
    name: micro-bot
  annotations:
    name: "go.micro.bot"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-bot
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-bot
        micro: runtime
    spec:
      containers:
        - name: bot
          command: [
            "/micro",
            "bot",
            "--inputs=slack"
          ]
          image: bentoogood/micro:mtls
          imagePullPolicy: Always
          env:
          - name: MICRO_AUTH
            value: "service"
          - name: MICRO_AUTH_ADDRESS
            value: "micro-auth:8010"
          - name: MICRO_AUTH_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: micro-secrets
                key: auth_public_key
          - name: MICRO_BROKER
            value: "service"
          - name: MICRO_BROKER_ADDRESS
            value: "micro-broker:8001"
          - name: MICRO_REGISTRY
            value: "service"
          - name: MICRO_REGISTRY_ADDRESS
            value: "micro-registry:8000"
        - name: MICRO_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: micro-secrets
                key: slack


