apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-config
  labels:
    name: micro-config
    micro: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-config
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-config
        micro: runtime
    spec:
      containers:
      - name: micro-config
        env:
        # - name: MICRO_AUTH
        #   value: "jwt"
        # - name: MICRO_AUTH_PUBLIC_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: micro-secrets
        #       key: auth_public_key
        # - name: MICRO_AUTH_PRIVATE_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: micro-secrets
        #       key: auth_private_key
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8080"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        # - name: MICRO_BROKER
        #   value: "nats"
        # - name: MICRO_BROKER_ADDRESS
        #   value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster"
        - name: MICRO_REGISTRY_SECURE
          value: "true"
        - name: MICRO_CERTIFICATE_AUTHORITIES
          value: "/certs/registry/ca.crt"
        # - name: MICRO_STORE
        #   value: "cockroach"
        # - name: MICRO_STORE_ADDRESS
        #   value: "postgres://root@cockroachdb-public:26257/?sslmode=disable"
        image: bentoogood/micro:mtls
        imagePullPolicy: Always
        command:
        - /micro
        - config
        ports:
        - containerPort: 8080
          name: service
        volumeMounts:
        - name: etcd-client-certs
          mountPath: "/certs/registry"
          readOnly: true
      volumes:
      - name: etcd-client-certs
        secret:
          secretName: etcd-client-certs