apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-network-api
  labels:
    micro: runtime
    name: micro-network-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-network-api
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-network-api
        micro: runtime
    spec:
      containers:
        - name: micro-network-api
          command: [
                "/micro",
                "--server_address=0.0.0.0:9090",
                "network",
                "api",
          ]
          env:
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats-cluster"
          - name: MICRO_PROXY
            value: "go.micro.proxy"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
          - name: MICRO_REGISTER_TTL
            value: "60"
          - name: MICRO_REGISTER_INTERVAL
            value: "30"
          image: micro/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: api-port
