apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-proxy
  labels:
    micro: runtime
    name: micro-proxy
  annotations:
    name: "go.micro.proxy"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-proxy
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-proxy
        micro: runtime
    spec:
      containers:
      - name: proxy
        env:
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local"
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROXY_ADDRESS
          value: "0.0.0.0:443"
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8081"
        - name: MICRO_LOG_LEVEL
          value: "trace"
        - name: MICRO_REGISTRY_ADDRESS
          value: "micro-registry:8000"
        - name: MICRO_ENABLE_ACME
          value: "true"
        - name: MICRO_ACME_PROVIDER
          value: certmagic
        - name: MICRO_ACME_HOSTS
          value: 'proxy.m3o.com'
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: cloudflare
              name: micro-secrets
        args:
        - proxy
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https-port
        - containerPort: 8081
          name: proxy-port