apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-router
  labels:
    micro: runtime
    name: micro-router
  annotations:
    name: "go.micro.router"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-router
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-router
        micro: runtime
    spec:
      containers:
      - name: router
        env:
        - name: MICRO_LOG_LEVEL
          value: "trace"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_ENABLE_ACME
          value: "true"
        args:
        - router
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: router-port
