apiVersion: v1
kind: Secret
metadata:
  name: micro-secrets
type: Opaque
data:
  slack: // token from slack app
  cloudflare: // token from cloudflare
  auth_public_key: // base64 encoded token
  auth_private_key: // base64 encoded token
