# apiVersion: v1
# kind: Service
# metadata:
#   name: micro-web
#   namespace: default
#   labels:
#     name: micro-web
#     micro: runtime
# spec:
#   ports:
#   - name: https
#     port: 443
#     targetPort: 443
#   selector:
#     name: micro-web
#     micro: runtime
#   type: LoadBalancer
