## Install NATS Operator
#
# kubectl apply -f https://github.com/nats-io/nats-operator/releases/latest/download/00-prereqs.yaml
# kubectl apply -f https://github.com/nats-io/nats-operator/releases/latest/download/10-deployment.yaml
#
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
spec:
  size: 3
  version: "1.3.0"
