apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: message-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: message-web
  template:
    metadata:
      labels:
        name: message-web
    spec:
      containers:
        - name: message-web
          command: [
		    "/message-web"
          ]
          env:
          - name: MICRO_REGISTRY
            value: "consul"
          - name: MICRO_REGISTRY_ADDRESS
            value: "consul-consul-server"
          image: microhq/message-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: web-port
