apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-config
  labels:
    name: micro-config
    micro: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-config
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-config
        micro: runtime
    spec:
      containers:
      - name: micro-config
        env:
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8080"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_CONFIG_DATABASE
          value: "store"
        image: micro/micro
        imagePullPolicy: Always
        command:
        - /micro
        - config
        ports:
        - containerPort: 8080
          name: service
