name: Push cells

on:
  push:
    branches:
      - master
      - bugfix/cells

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Build cells
      run: cd service/runtime/cells; bash build.sh
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
