name: Platform Image

on:
  push:
    branches:
      - master
      - new_runtime_interface
    tags:
      - v2.*
      - v3.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Fetch tags
      run: git fetch --prune --unshallow

    - name: Replace platform profile
      id: replace-profile
      run: |
        go mod edit -replace github.com/micro/micro/profile/platform/v3=./profile/platform
        go mod edit -replace google.golang.org/grpc=google.golang.org/grpc@v1.26.0

    - name: Build profile
      run: |
        go run . init --profile=platform --output=profile.go

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: micro/platform
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        snapshot: true